apiVersion: v1
kind: Service
metadata:
  name: orders-app-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    name: orders-app-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort

