apiVersion: v2
name: orders-app-chart
description: A Helm chart for orders-app-service
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.1.4
