replicaCount: 1
namespace: default

image:
  repository: gcr.io/setel-298305/setel-orders-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  containerPort: 80
  nodePort: 30000

config:
  paymentsSvcHostname: payments-app-svc.default.svc.cluster.local
  databaseHost: orders-chart-postgresql.default.svc.cluster.local
  databasePort: 5432
  databaseName: orders
  databaseUsername: seteladmin

secret:
  databasePassword: seteladmin

postgresql:
  postgresqlUsername: seteladmin
  postgresqlPassword: seteladmin
  postgresqlDatabase: orders
